graphhopper:
  datareader.file: ""
  graph.location: graph-cache
  import.osm.ignored_highways: motorway,trunk,motorway_link,trunk_link
  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
  profiles_ch:
    - profile: foot
  profiles_lm: []
