graphhopper:
  datareader.file: ""
  graph.location: graph-cache
  import.osm.ignored_highways: motorway,trunk,motorway_link,trunk_link
  profiles:
    - name: foot
      vehicle: foot
      weighting: custom
      custom_model:
        distance_influence: 15
        priority:
          - if: "road_access == DESTINATION"
            multiply_by: 0.1
  profiles_ch:
    - profile: foot
  profiles_lm: []
